### ISSUE TITLE
Web project does not run

### ISSUE THREAD

**Issue by codedghost** [codedghost/CodedChatbot#15]
I suspect this is because Unity is not configured in this project yet. After doing some digging, should we not just use the .Net Core IoC?

**Comment by Farami** [comment]
I guess we could. I've used Unity extensively so I know that one quite well, I haven't used Cores IoC yet.

**Comment by codedghost** [comment]
I'm not sure the .Net Core IoC is quite relevant for how we're loading some things in. I've ended up using Unity in the Chatbot project, and using .Net Core IoC on the web project to load in the relevant Helpers and the db context. See full-web-project branch.
